### ISSUE TITLE
Problems with newer OpenJDK

### ISSUE THREAD

**Issue by veitveit** [ProtProtocols/docker-launcher#10]
It looks that there is some incompatibility with OpenJDK (version 10.0.1):

Error:
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

The reason lies in a missing openjfx library.

On the other side, it works with OpenJDK 1.8 as the openjfx has been installed in my computer (OpenSUSE)

**Comment by jgriss** [comment]
@veitveit Thanks for testing it!

Is it possible to install openjfx for OpenJDK 10.0.1 on your system? Also, I am not sure that this is something I can fix since the application will always fail if a class is missing in the classpath.

Oracle Java always ships the OpenJFX classes automatically.

**Comment by jgriss** [comment]
Oracle decided to no longer ship JavaFX directly with Java. JavaFX has become a separate project.

JavaFX provide OS dependent packages but maven dependencies also exist. Therefore, it might either be necessary to A) create different versions of `docker-launcher` or B) update the installation instructions.
